name: Build and Push App To ACR

on:
  push:
    branches:
      - main
    paths:
      - "2048-game/**"

permissions:
  contents: read

jobs:
  deploy-flask:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: docker build -t 2048game:latest ./app

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: "2048game:latest"
          format: "table"
          exit-code: "0" # Set to "1" to fail on findings
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Tag image for ACR
        run: docker tag 2048game:latest ${{ secrets.ACR_LOGIN_SERVER }}/2048game:latest

      - name: Push Docker image to ACR
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/2048game:latest
